---
version: '2.4'
#add non core CCD services here

services:
  rd-professional-api:
    image: hmctspublic.azurecr.io/rd/professional-api:pr-1542 # ga-master
    #image: localdebug_rd-professional-api:latest
    container_name: rd-professional-api
    environment:
      POSTGRES_USERNAME: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_HOST: ccd-shared-database
      POSTGRES_PORT: 5432
      S2S_URL: http://service-auth-provider-api:8080
      USER_PROFILE_URL: http://rd-user-profile-api:8091
      OIDC_ISSUER_URL: "${IDAM_STUB_SERVICE_NAME:-http://rse-idam-simulator:5000}/openam/oauth2/hmcts"
      OPEN_ID_API_BASE_URI: "${IDAM_STUB_SERVICE_NAME:-http://rse-idam-simulator:5000}/o"
      IDAM_URL: "${IDAM_STUB_SERVICE_NAME:-http://rse-idam-simulator:5000}"
      CCD_URL: http://ccd-user-profile-api:4453
      AUTH_IDAM_CLIENT_BASEURL: "${IDAM_STUB_SERVICE_NAME:-http://rse-idam-simulator:5000}"
      LAUNCH_DARKLY_ENV: aat
      LD_SDK_KEY: sdk-b1310c4a-e522-4512-9e68-d75d23b04c5d
      ACCOUNT_NAME: devstoreaccount1 # dummy value
      ACCOUNT_KEY: Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw== # dummy value
      PROFESSIONAL_API_S2S_SECRET: "${IDAM_KEY_CCD_GATEWAY}"
      PRD_S2S_AUTHORISED_SERVICES: rd_professional_api,rd_user_profile_api,xui_webapp,finrem_payment_service,fpl_case_service,iac,aac_manage_case_assignment,divorce_frontend,am_org_role_mapping_service
      #JAVA_TOOL_OPTIONS: '-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005'
    healthcheck:
      interval: 10s
      timeout: 10s
      retries: 10
    ports:
      - 8090:8090
      #- 5005:5005
    depends_on:
      - ccd-shared-database
    networks:
      - ccd-network

  rd-user-profile-api:
    image: hmctspublic.azurecr.io/rd/user-profile-api:latest
    #image: localdebug_rd-user-api:latest
    container_name: rd-user-profile-api
    environment:
      POSTGRES_USERNAME: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_HOST: ccd-shared-database
      POSTGRES_PORT: 5432
      CCD_URL: http://ccd-user-profile-api:4453
      OIDC_ISSUER_URL: "${IDAM_STUB_SERVICE_NAME:-http://rse-idam-simulator:5000}/openam/oauth2/hmcts"
      OPEN_ID_API_BASE_URI: "${IDAM_STUB_SERVICE_NAME:-http://rse-idam-simulator:5000}/o"
      IDAM_URL: "${IDAM_STUB_SERVICE_NAME:-http://rse-idam-simulator:5000}"
      AUTH_IDAM_CLIENT_BASEURL: "${IDAM_STUB_SERVICE_NAME:-http://rse-idam-simulator:5000}"
      S2S_URL: http://service-auth-provider-api:8080
      USER_PROFILE_API_S2S_SECRET: "${IDAM_KEY_CCD_GATEWAY}"
      #JAVA_TOOL_OPTIONS: '-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5006'
    healthcheck:
      interval: 10s
      timeout: 10s
      retries: 10
    ports:
      - 8091:8091
      #- 5006:5006
    depends_on:
      - ccd-shared-database
    networks:
      - ccd-network

  am-org-role-mapping-service:
    image: hmctspublic.azurecr.io/am/org-role-mapping-service:pr-1769
    # image: localdebug_amorg:latest
    container_name: am-org-role-mapping-service
    environment:
      IDAM_S2S_URL: http://service-auth-provider-api:8080
      IDAM_USER_URL: http://rse-idam-simulator:5000
      OIDC_ISSUER_URL: http://rse-idam-simulator:5000/openam/oauth2/hmcts
      OPEN_ID_API_BASE_URI: "http://rse-idam-simulator:5000/o"
      S2S_URL: http://service-auth-provider-api:8080
      AM_ORG_ROLE_MAPPING_S2S_AUTHORISED_SERVICES: ccd_gw,am_org_role_mapping_service,am_role_assignment_service,xui_webapp,am_role_assignment_refresh_batch
      ROLE_ASSIGNMENT_APP_URL: http://am-role-assignment-service:4096
      JUDICIAL_BOOKING_APP_URL: http://am-judicial-booking-service-aat.service.core-compute-aat.internal
      CASE_WORKER_REF_APP_URL: http://rd-caseworker-ref-api-aat.service.core-compute-aat.internal
      JUDICIAL_REF_APP_URL: http://rd-judicial-api-aat.service.core-compute-aat.internal
      JUDICIAL_REF_APP_V2_ACTIVE: "false"
      JUDICIAL_REF_APP_V2_FILTER_AUTHS_BY_APP_ID: "false"
      LAUNCH_DARKLY_ENV: aat
      LD_SDK_KEY: sdk-28c71191-54b1-4d81-8c8d-add52b134bc7
      AMQP_HOST: rd-servicebus-aat.servicebus.windows.net
      AMQP_SHARED_ACCESS_KEY_NAME: SendAndListenSharedAccessKey
      AMQP_ENABLED: "false"
      TRUST_ALL_CERTS: "true"
      CRD_TOPIC_NAME: rd-caseworker-topic-aat
      CRD_SUBSCRIPTION_NAME: rd-caseworker-subscription-aat
      JRD_TOPIC_NAME: rd-judicial-topic-aat
      JRD_SUBSCRIPTION_NAME: rd-judicial-subscription-aat
      ORG_ROLE_MAPPING_IDAM_ADMIN_USERID: "local-prd-admin@gmail.com"
      ORG_ROLE_MAPPING_DB_PORT: 5432
      ORG_ROLE_MAPPING_DB_NAME: org_role_mapping
      ORG_ROLE_MAPPING_DB_HOST: ccd-shared-database
      ORG_ROLE_MAPPING_DB_USERNAME: "${DB_USERNAME}"
      ORG_ROLE_MAPPING_DB_PASSWORD: "${DB_PASSWORD}"
      ORG_ROLE_MAPPING_DB_OPTIONS: "?stringtype=unspecified"
      REFRESH_JOB:
      TESTING_SUPPORT_ENABLED: "true"
      APPLICATION_LOGGING_LEVEL: INFO
      RUN_LD_ON_STARTUP: "true"
      PROFESSIONAL_REF_APP_URL: "http://rd-professional-api:8090"
      PROFESSIONAL_REFDATA_PAGE_SIZE: 2
      PROFESSIONAL_SCHEDULING_ENABLED: "true"
      CRON_P2_ORGS_STALE_PROFILES: "* * 0 * * *"
      CRON_P3_ORG_CHANGES: "* * 0 * * *"
      USER_REFRESH_CRON: "*/2 * * * * *"
      TOLERANCE: 10
      AM_ROLE_ASSIGNMENT_SERVICE_SECRET: "${IDAM_KEY_AM_ROLE_ASSIGNMENT}"
      AM_ORG_ROLE_MAPPING_SERVICE_SECRET: "${IDAM_KEY_AM_ORG_ROLE_MAPPING}"
      ORG_ROLE_MAPPING_IDAM_ADMIN_PASSWORD: "Pa55word11"
      # JAVA_TOOL_OPTIONS: '-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5010'
    ports:
      - 4098:4098
      # - 5010:5010
    networks:
      - ccd-network
    depends_on:
      - ccd-shared-database
    links:
      - ccd-shared-database

networks:
  ccd-network:
    external: true
